/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ConfigureImport } from './routes/configure'
import { Route as AuthImport } from './routes/auth'
import { Route as IndexImport } from './routes/index'
import { Route as AboutIndexImport } from './routes/about/index'
import { Route as TestTestpathImport } from './routes/test/testpath'
import { Route as AboutEditImport } from './routes/about/edit'

// Create/Update Routes

const ConfigureRoute = ConfigureImport.update({
  id: '/configure',
  path: '/configure',
  getParentRoute: () => rootRoute,
} as any)

const AuthRoute = AuthImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AboutIndexRoute = AboutIndexImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => rootRoute,
} as any)

const TestTestpathRoute = TestTestpathImport.update({
  id: '/test/testpath',
  path: '/test/testpath',
  getParentRoute: () => rootRoute,
} as any)

const AboutEditRoute = AboutEditImport.update({
  id: '/about/edit',
  path: '/about/edit',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/configure': {
      id: '/configure'
      path: '/configure'
      fullPath: '/configure'
      preLoaderRoute: typeof ConfigureImport
      parentRoute: typeof rootRoute
    }
    '/about/edit': {
      id: '/about/edit'
      path: '/about/edit'
      fullPath: '/about/edit'
      preLoaderRoute: typeof AboutEditImport
      parentRoute: typeof rootRoute
    }
    '/test/testpath': {
      id: '/test/testpath'
      path: '/test/testpath'
      fullPath: '/test/testpath'
      preLoaderRoute: typeof TestTestpathImport
      parentRoute: typeof rootRoute
    }
    '/about/': {
      id: '/about/'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/configure': typeof ConfigureRoute
  '/about/edit': typeof AboutEditRoute
  '/test/testpath': typeof TestTestpathRoute
  '/about': typeof AboutIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/configure': typeof ConfigureRoute
  '/about/edit': typeof AboutEditRoute
  '/test/testpath': typeof TestTestpathRoute
  '/about': typeof AboutIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/configure': typeof ConfigureRoute
  '/about/edit': typeof AboutEditRoute
  '/test/testpath': typeof TestTestpathRoute
  '/about/': typeof AboutIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/configure'
    | '/about/edit'
    | '/test/testpath'
    | '/about'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/configure' | '/about/edit' | '/test/testpath' | '/about'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/configure'
    | '/about/edit'
    | '/test/testpath'
    | '/about/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ConfigureRoute: typeof ConfigureRoute
  AboutEditRoute: typeof AboutEditRoute
  TestTestpathRoute: typeof TestTestpathRoute
  AboutIndexRoute: typeof AboutIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ConfigureRoute: ConfigureRoute,
  AboutEditRoute: AboutEditRoute,
  TestTestpathRoute: TestTestpathRoute,
  AboutIndexRoute: AboutIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/auth",
        "/configure",
        "/about/edit",
        "/test/testpath",
        "/about/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/auth": {
      "filePath": "auth.tsx"
    },
    "/configure": {
      "filePath": "configure.tsx"
    },
    "/about/edit": {
      "filePath": "about/edit.tsx"
    },
    "/test/testpath": {
      "filePath": "test/testpath.tsx"
    },
    "/about/": {
      "filePath": "about/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
